/*
 * tabla-content.mjs — Conținutul „Cântecelului tablei înmulțirii”.
 *
 * 10 capitole (înmulțirea cu 1 … cu 10), fiecare cu:
 *   - theme:  obiectul vizual al capitolului + culorile scenei;
 *   - intro:  salutul + trucul de memorare al capitolului;
 *   - verses: cele 10 înmulțiri — vocea narează operația și rezultatul
 *             („Doi ori patru fac opt!”), iar lista de pe ecran se
 *             completează rând cu rând;
 *   - outro:  încurajarea de final.
 *
 * `a`,`b` = factorii; `r` = rezultatul; `rWord` = rezultatul în litere (TTS).
 */

export const CHAPTERS = [
  {
    n: 1,
    theme: { object: "star", objectName: "steluțe", bg1: "#312e81", bg2: "#6d28d9", accent: "#fbbf24", card: "#fef3c7" },
    intro: [
      "Salut! Sunt Steluțul Socotel și cântăm tabla înmulțirii!",
      "Azi: înmulțirea cu unu — cea mai ușoară dintre toate.",
      "Orice număr ori unu rămâne exact el. Hai să cântăm!",
    ],
    trick: "Orice număr × 1 rămâne la fel!",
    verses: [
      { a: 1, b: 1, r: 1, rWord: "unu" },
      { a: 1, b: 2, r: 2, rWord: "doi" },
      { a: 1, b: 3, r: 3, rWord: "trei" },
      { a: 1, b: 4, r: 4, rWord: "patru" },
      { a: 1, b: 5, r: 5, rWord: "cinci" },
      { a: 1, b: 6, r: 6, rWord: "șase" },
      { a: 1, b: 7, r: 7, rWord: "șapte" },
      { a: 1, b: 8, r: 8, rWord: "opt" },
      { a: 1, b: 9, r: 9, rWord: "nouă" },
      { a: 1, b: 10, r: 10, rWord: "zece" },
    ],
    outro: ["Bravo! Aceasta este toată tabla cu unu.", "Repet-o și tu, cu voce tare!"],
  },
  {
    n: 2,
    theme: { object: "duck", objectName: "rățuște", bg1: "#0c4a6e", bg2: "#0284c7", accent: "#facc15", card: "#e0f2fe" },
    intro: [
      "Înmulțirea cu doi înseamnă dublul: fiecare rățușcă vine cu perechea ei!",
      "Hai să cântăm!",
    ],
    trick: "× 2 = dublul: numărul + perechea lui!",
    verses: [
      { a: 2, b: 1, r: 2, rWord: "doi" },
      { a: 2, b: 2, r: 4, rWord: "patru" },
      { a: 2, b: 3, r: 6, rWord: "șase" },
      { a: 2, b: 4, r: 8, rWord: "opt" },
      { a: 2, b: 5, r: 10, rWord: "zece" },
      { a: 2, b: 6, r: 12, rWord: "doisprezece" },
      { a: 2, b: 7, r: 14, rWord: "paisprezece" },
      { a: 2, b: 8, r: 16, rWord: "șaisprezece" },
      { a: 2, b: 9, r: 18, rWord: "optsprezece" },
      { a: 2, b: 10, r: 20, rWord: "douăzeci" },
    ],
    outro: ["Bravo! Aceasta este toată tabla cu doi.", "Repet-o și tu, cu voce tare!"],
  },
  {
    n: 3,
    theme: { object: "flower", objectName: "flori", bg1: "#14532d", bg2: "#16a34a", accent: "#f472b6", card: "#fce7f3" },
    intro: [
      "La înmulțirea cu trei, adăugăm mereu încă trei flori în buchet!",
      "Hai să cântăm!",
    ],
    trick: "× 3 = încă un grup de 3, de fiecare dată!",
    verses: [
      { a: 3, b: 1, r: 3, rWord: "trei" },
      { a: 3, b: 2, r: 6, rWord: "șase" },
      { a: 3, b: 3, r: 9, rWord: "nouă" },
      { a: 3, b: 4, r: 12, rWord: "doisprezece" },
      { a: 3, b: 5, r: 15, rWord: "cincisprezece" },
      { a: 3, b: 6, r: 18, rWord: "optsprezece" },
      { a: 3, b: 7, r: 21, rWord: "douăzeci și unu" },
      { a: 3, b: 8, r: 24, rWord: "douăzeci și patru" },
      { a: 3, b: 9, r: 27, rWord: "douăzeci și șapte" },
      { a: 3, b: 10, r: 30, rWord: "treizeci" },
    ],
    outro: ["Bravo! Aceasta este toată tabla cu trei.", "Repet-o și tu, cu voce tare!"],
  },
  {
    n: 4,
    theme: { object: "apple", objectName: "mere", bg1: "#7f1d1d", bg2: "#dc2626", accent: "#4ade80", card: "#dcfce7" },
    intro: [
      "Patru e dublul lui doi: la înmulțirea cu patru, dublezi de două ori!",
      "Hai să cântăm!",
    ],
    trick: "× 4 = dublezi, apoi mai dublezi o dată!",
    verses: [
      { a: 4, b: 1, r: 4, rWord: "patru" },
      { a: 4, b: 2, r: 8, rWord: "opt" },
      { a: 4, b: 3, r: 12, rWord: "doisprezece" },
      { a: 4, b: 4, r: 16, rWord: "șaisprezece" },
      { a: 4, b: 5, r: 20, rWord: "douăzeci" },
      { a: 4, b: 6, r: 24, rWord: "douăzeci și patru" },
      { a: 4, b: 7, r: 28, rWord: "douăzeci și opt" },
      { a: 4, b: 8, r: 32, rWord: "treizeci și doi" },
      { a: 4, b: 9, r: 36, rWord: "treizeci și șase" },
      { a: 4, b: 10, r: 40, rWord: "patruzeci" },
    ],
    outro: ["Bravo! Aceasta este toată tabla cu patru.", "Repet-o și tu, cu voce tare!"],
  },
  {
    n: 5,
    theme: { object: "bee", objectName: "albinuțe", bg1: "#713f12", bg2: "#d97706", accent: "#fde047", card: "#fef9c3" },
    intro: [
      "Secretul înmulțirii cu cinci: rezultatul se termină mereu în cinci sau în zero!",
      "Hai să cântăm!",
    ],
    trick: "× 5 se termină mereu în 5 sau 0!",
    verses: [
      { a: 5, b: 1, r: 5, rWord: "cinci" },
      { a: 5, b: 2, r: 10, rWord: "zece" },
      { a: 5, b: 3, r: 15, rWord: "cincisprezece" },
      { a: 5, b: 4, r: 20, rWord: "douăzeci" },
      { a: 5, b: 5, r: 25, rWord: "douăzeci și cinci" },
      { a: 5, b: 6, r: 30, rWord: "treizeci" },
      { a: 5, b: 7, r: 35, rWord: "treizeci și cinci" },
      { a: 5, b: 8, r: 40, rWord: "patruzeci" },
      { a: 5, b: 9, r: 45, rWord: "patruzeci și cinci" },
      { a: 5, b: 10, r: 50, rWord: "cincizeci" },
    ],
    outro: ["Bravo! Aceasta este toată tabla cu cinci.", "Repet-o și tu, cu voce tare!"],
  },
  {
    n: 6,
    theme: { object: "ladybug", objectName: "buburuze", bg1: "#3f6212", bg2: "#65a30d", accent: "#f87171", card: "#fee2e2" },
    intro: [
      "Șase e dublul lui trei: dacă știi tabla cu trei, o dublezi și gata!",
      "Hai să cântăm!",
    ],
    trick: "× 6 = tabla cu 3, dublată!",
    verses: [
      { a: 6, b: 1, r: 6, rWord: "șase" },
      { a: 6, b: 2, r: 12, rWord: "doisprezece" },
      { a: 6, b: 3, r: 18, rWord: "optsprezece" },
      { a: 6, b: 4, r: 24, rWord: "douăzeci și patru" },
      { a: 6, b: 5, r: 30, rWord: "treizeci" },
      { a: 6, b: 6, r: 36, rWord: "treizeci și șase" },
      { a: 6, b: 7, r: 42, rWord: "patruzeci și doi" },
      { a: 6, b: 8, r: 48, rWord: "patruzeci și opt" },
      { a: 6, b: 9, r: 54, rWord: "cincizeci și patru" },
      { a: 6, b: 10, r: 60, rWord: "șaizeci" },
    ],
    outro: ["Bravo! Aceasta este toată tabla cu șase.", "Repet-o și tu, cu voce tare!"],
  },
  {
    n: 7,
    theme: { object: "balloon", objectName: "baloane", bg1: "#581c87", bg2: "#9333ea", accent: "#fb923c", card: "#ffedd5" },
    intro: [
      "Șapte — ca zilele săptămânii! Tabla cu șapte cere puțin curaj, dar cu baloane zboară ușor!",
      "Hai să cântăm!",
    ],
    trick: "7 — ca zilele săptămânii!",
    verses: [
      { a: 7, b: 1, r: 7, rWord: "șapte" },
      { a: 7, b: 2, r: 14, rWord: "paisprezece" },
      { a: 7, b: 3, r: 21, rWord: "douăzeci și unu" },
      { a: 7, b: 4, r: 28, rWord: "douăzeci și opt" },
      { a: 7, b: 5, r: 35, rWord: "treizeci și cinci" },
      { a: 7, b: 6, r: 42, rWord: "patruzeci și doi" },
      { a: 7, b: 7, r: 49, rWord: "patruzeci și nouă" },
      { a: 7, b: 8, r: 56, rWord: "cincizeci și șase" },
      { a: 7, b: 9, r: 63, rWord: "șaizeci și trei" },
      { a: 7, b: 10, r: 70, rWord: "șaptezeci" },
    ],
    outro: ["Bravo! Aceasta este toată tabla cu șapte.", "Repet-o și tu, cu voce tare!"],
  },
  {
    n: 8,
    theme: { object: "fish", objectName: "peștișori", bg1: "#164e63", bg2: "#0891b2", accent: "#fb923c", card: "#cffafe" },
    intro: [
      "Opt e dublul lui patru — iar caracatița are opt brațe, numai bune la socotit!",
      "Hai să cântăm!",
    ],
    trick: "× 8 = dublul lui × 4!",
    verses: [
      { a: 8, b: 1, r: 8, rWord: "opt" },
      { a: 8, b: 2, r: 16, rWord: "șaisprezece" },
      { a: 8, b: 3, r: 24, rWord: "douăzeci și patru" },
      { a: 8, b: 4, r: 32, rWord: "treizeci și doi" },
      { a: 8, b: 5, r: 40, rWord: "patruzeci" },
      { a: 8, b: 6, r: 48, rWord: "patruzeci și opt" },
      { a: 8, b: 7, r: 56, rWord: "cincizeci și șase" },
      { a: 8, b: 8, r: 64, rWord: "șaizeci și patru" },
      { a: 8, b: 9, r: 72, rWord: "șaptezeci și doi" },
      { a: 8, b: 10, r: 80, rWord: "optzeci" },
    ],
    outro: ["Bravo! Aceasta este toată tabla cu opt.", "Repet-o și tu, cu voce tare!"],
  },
  {
    n: 9,
    theme: { object: "butterfly", objectName: "fluturași", bg1: "#4c1d95", bg2: "#7c3aed", accent: "#5eead4", card: "#ccfbf1" },
    intro: [
      "Truc magic la tabla cu nouă: adună cifrele rezultatului — fac mereu nouă!",
      "Optsprezece: unu plus opt — nouă!",
      "Hai să cântăm!",
    ],
    trick: "La × 9, cifrele rezultatului adunate dau 9!",
    verses: [
      { a: 9, b: 1, r: 9, rWord: "nouă" },
      { a: 9, b: 2, r: 18, rWord: "optsprezece" },
      { a: 9, b: 3, r: 27, rWord: "douăzeci și șapte" },
      { a: 9, b: 4, r: 36, rWord: "treizeci și șase" },
      { a: 9, b: 5, r: 45, rWord: "patruzeci și cinci" },
      { a: 9, b: 6, r: 54, rWord: "cincizeci și patru" },
      { a: 9, b: 7, r: 63, rWord: "șaizeci și trei" },
      { a: 9, b: 8, r: 72, rWord: "șaptezeci și doi" },
      { a: 9, b: 9, r: 81, rWord: "optzeci și unu" },
      { a: 9, b: 10, r: 90, rWord: "nouăzeci" },
    ],
    outro: ["Bravo! Aceasta este toată tabla cu nouă.", "Repet-o și tu, cu voce tare!"],
  },
  {
    n: 10,
    theme: { object: "candy", objectName: "bomboane", bg1: "#831843", bg2: "#db2777", accent: "#a5f3fc", card: "#fce7f3" },
    intro: [
      "Cea mai dulce tablă: la înmulțirea cu zece, pui un zero la coadă și gata!",
      "Hai să cântăm!",
    ],
    trick: "× 10 = pui un 0 la coadă!",
    verses: [
      { a: 10, b: 1, r: 10, rWord: "zece" },
      { a: 10, b: 2, r: 20, rWord: "douăzeci" },
      { a: 10, b: 3, r: 30, rWord: "treizeci" },
      { a: 10, b: 4, r: 40, rWord: "patruzeci" },
      { a: 10, b: 5, r: 50, rWord: "cincizeci" },
      { a: 10, b: 6, r: 60, rWord: "șaizeci" },
      { a: 10, b: 7, r: 70, rWord: "șaptezeci" },
      { a: 10, b: 8, r: 80, rWord: "optzeci" },
      { a: 10, b: 9, r: 90, rWord: "nouăzeci" },
      { a: 10, b: 10, r: 100, rWord: "o sută" },
    ],
    outro: ["Bravo! Ai terminat întreaga tablă a înmulțirii!", "Repet-o și tu, cu voce tare!"],
  },
];
