/*
 * tabla-content.mjs — Conținutul „Cântecelului tablei înmulțirii”.
 *
 * 10 capitole (înmulțirea cu 1 … cu 10), fiecare cu:
 *   - theme:  obiectul vizual al capitolului + culorile scenei;
 *   - intro:  salutul + trucul de memorare al capitolului;
 *   - verses: 10 versuri în rime — rima „cheamă” rezultatul, ca să-l
 *             anticipeze copilul înainte să fie rostit;
 *   - recap:  numărarea din N în N (skip counting), cântată cifră cu cifră;
 *   - outro:  încurajarea de final.
 *
 * `cue` = versul-indiciu (rimează cu rezultatul); `a`,`b` = factorii; `r` = rezultatul.
 */

export const CHAPTERS = [
  {
    n: 1,
    theme: { object: "star", objectName: "steluțe", bg1: "#312e81", bg2: "#6d28d9", accent: "#fbbf24", card: "#fef3c7" },
    intro: [
      "Salut! Sunt Steluțul Socotel și cântăm tabla înmulțirii!",
      "Azi: înmulțirea cu unu — cea mai ușoară dintre toate.",
      "Orice număr ori unu rămâne exact el. Hai să cântăm!",
    ],
    trick: "Orice număr × 1 rămâne la fel!",
    verses: [
      { cue: "O steluță pe alun:", a: 1, b: 1, r: 1, rWord: "unu" },
      { cue: "Două stele pentru noi:", a: 1, b: 2, r: 2, rWord: "doi" },
      { cue: "Stele ca trei ghiocei:", a: 1, b: 3, r: 3, rWord: "trei" },
      { cue: "Stele-n cer ca la teatru:", a: 1, b: 4, r: 4, rWord: "patru" },
      { cue: "Stele mici cât cinci opinci:", a: 1, b: 5, r: 5, rWord: "cinci" },
      { cue: "Stele-au coborât pe case:", a: 1, b: 6, r: 6, rWord: "șase" },
      { cue: "Stele-apar în plină noapte:", a: 1, b: 7, r: 7, rWord: "șapte" },
      { cue: "Numărăm și facem hop:", a: 1, b: 8, r: 8, rWord: "opt" },
      { cue: "Stele ude de la rouă:", a: 1, b: 9, r: 9, rWord: "nouă" },
      { cue: "Noaptea nu mai pare rece:", a: 1, b: 10, r: 10, rWord: "zece" },
    ],
    recapIntro: "Hai să numărăm din unu în unu:",
    recapWords: ["unu", "doi", "trei", "patru", "cinci", "șase", "șapte", "opt", "nouă", "zece"],
    outro: ["Bravo! Tabla cu unu e a ta!", "Ne vedem la înmulțirea cu doi!"],
  },
  {
    n: 2,
    theme: { object: "duck", objectName: "rățuște", bg1: "#0c4a6e", bg2: "#0284c7", accent: "#facc15", card: "#e0f2fe" },
    intro: [
      "Înmulțirea cu doi înseamnă dublul: fiecare rățușcă vine cu perechea ei!",
      "Hai să cântăm!",
    ],
    trick: "× 2 = dublul: numărul + perechea lui!",
    verses: [
      { cue: "Două rațe stau în ploi:", a: 2, b: 1, r: 2, rWord: "doi" },
      { cue: "Mac, mac, mac, ca la teatru:", a: 2, b: 2, r: 4, rWord: "patru" },
      { cue: "Rațele pornesc spre case:", a: 2, b: 3, r: 6, rWord: "șase" },
      { cue: "Mărul de pe mal e copt:", a: 2, b: 4, r: 8, rWord: "opt" },
      { cue: "Apa lacului e rece:", a: 2, b: 5, r: 10, rWord: "zece" },
      { cue: "Rața prin zăpadă trece:", a: 2, b: 6, r: 12, rWord: "doisprezece" },
      { cue: "Rața la înot se-ntrece:", a: 2, b: 7, r: 14, rWord: "paisprezece" },
      { cue: "Vântul peste lac tot trece:", a: 2, b: 8, r: 16, rWord: "șaisprezece" },
      { cue: "Seara-n baltă se petrece:", a: 2, b: 9, r: 18, rWord: "optsprezece" },
      { cue: "Hai cu rațele să pleci:", a: 2, b: 10, r: 20, rWord: "douăzeci" },
    ],
    recapIntro: "Numărăm din doi în doi:",
    recapWords: ["doi", "patru", "șase", "opt", "zece", "doisprezece", "paisprezece", "șaisprezece", "optsprezece", "douăzeci"],
    outro: ["Bravo! Dublul nu mai are secrete!", "Urmează înmulțirea cu trei!"],
  },
  {
    n: 3,
    theme: { object: "flower", objectName: "flori", bg1: "#14532d", bg2: "#16a34a", accent: "#f472b6", card: "#fce7f3" },
    intro: [
      "La înmulțirea cu trei, adăugăm mereu încă trei flori în buchet!",
      "Hai să cântăm!",
    ],
    trick: "× 3 = încă un grup de 3, de fiecare dată!",
    verses: [
      { cue: "O floare lângă tei:", a: 3, b: 1, r: 3, rWord: "trei" },
      { cue: "Flori frumoase lângă case:", a: 3, b: 2, r: 6, rWord: "șase" },
      { cue: "Floarea bea un strop de rouă:", a: 3, b: 3, r: 9, rWord: "nouă" },
      { cue: "Primăvara nu e rece:", a: 3, b: 4, r: 12, rWord: "doisprezece" },
      { cue: "Pe alee lumea trece:", a: 3, b: 5, r: 15, rWord: "cincisprezece" },
      { cue: "Nicio floare nu se-ntrece:", a: 3, b: 6, r: 18, rWord: "optsprezece" },
      { cue: "A-nflorit în deal alunul:", a: 3, b: 7, r: 21, rWord: "douăzeci și unu" },
      { cue: "Fluturii dansează teatru:", a: 3, b: 8, r: 24, rWord: "douăzeci și patru" },
      { cue: "Petalele vorbesc în șoapte:", a: 3, b: 9, r: 27, rWord: "douăzeci și șapte" },
      { cue: "Buchetele nu-s deloc reci:", a: 3, b: 10, r: 30, rWord: "treizeci" },
    ],
    recapIntro: "Numărăm din trei în trei:",
    recapWords: ["trei", "șase", "nouă", "doisprezece", "cincisprezece", "optsprezece", "douăzeci și unu", "douăzeci și patru", "douăzeci și șapte", "treizeci"],
    outro: ["Bravo! Grădina ta de numere înflorește!", "Urmează înmulțirea cu patru!"],
  },
  {
    n: 4,
    theme: { object: "apple", objectName: "mere", bg1: "#7f1d1d", bg2: "#dc2626", accent: "#4ade80", card: "#dcfce7" },
    intro: [
      "Patru e dublul lui doi: la înmulțirea cu patru, dublezi de două ori!",
      "Hai să cântăm!",
    ],
    trick: "× 4 = dublezi, apoi mai dublezi o dată!",
    verses: [
      { cue: "Mere roșii ca la teatru:", a: 4, b: 1, r: 4, rWord: "patru" },
      { cue: "Mărul din livadă-i copt:", a: 4, b: 2, r: 8, rWord: "opt" },
      { cue: "Toamna printre pomi trece:", a: 4, b: 3, r: 12, rWord: "doisprezece" },
      { cue: "Niciun vierme nu le trece:", a: 4, b: 4, r: 16, rWord: "șaisprezece" },
      { cue: "Le culegi și-apoi petreci:", a: 4, b: 5, r: 20, rWord: "douăzeci" },
      { cue: "Coșul mare e albastru:", a: 4, b: 6, r: 24, rWord: "douăzeci și patru" },
      { cue: "Strudelul cu măr e copt:", a: 4, b: 7, r: 28, rWord: "douăzeci și opt" },
      { cue: "Împărțim la amândoi:", a: 4, b: 8, r: 32, rWord: "treizeci și doi" },
      { cue: "Le păstrăm în pod, în case:", a: 4, b: 9, r: 36, rWord: "treizeci și șase" },
      { cue: "Iarna merele-s mai reci:", a: 4, b: 10, r: 40, rWord: "patruzeci" },
    ],
    recapIntro: "Numărăm din patru în patru:",
    recapWords: ["patru", "opt", "doisprezece", "șaisprezece", "douăzeci", "douăzeci și patru", "douăzeci și opt", "treizeci și doi", "treizeci și șase", "patruzeci"],
    outro: ["Bravo! Coșul cu mere e plin!", "Urmează înmulțirea cu cinci!"],
  },
  {
    n: 5,
    theme: { object: "bee", objectName: "albinuțe", bg1: "#713f12", bg2: "#d97706", accent: "#fde047", card: "#fef9c3" },
    intro: [
      "Secretul înmulțirii cu cinci: rezultatul se termină mereu în cinci sau în zero!",
      "Hai să cântăm!",
    ],
    trick: "× 5 se termină mereu în 5 sau 0!",
    verses: [
      { cue: "O albină pe opinci:", a: 5, b: 1, r: 5, rWord: "cinci" },
      { cue: "Zboară lin și nu se-ntrece:", a: 5, b: 2, r: 10, rWord: "zece" },
      { cue: "Zumzetul prin flori trece:", a: 5, b: 3, r: 15, rWord: "cincisprezece" },
      { cue: "Duc polenul pe poteci:", a: 5, b: 4, r: 20, rWord: "douăzeci" },
      { cue: "Mierea place și la arici:", a: 5, b: 5, r: 25, rWord: "douăzeci și cinci" },
      { cue: "Fagurii nu-s deloc seci:", a: 5, b: 6, r: 30, rWord: "treizeci" },
      { cue: "Seara vin la licurici:", a: 5, b: 7, r: 35, rWord: "treizeci și cinci" },
      { cue: "Când e frig, afară nu pleci:", a: 5, b: 8, r: 40, rWord: "patruzeci" },
      { cue: "Miere pentru cei pitici:", a: 5, b: 9, r: 45, rWord: "patruzeci și cinci" },
      { cue: "Am ajuns la capăt, deci:", a: 5, b: 10, r: 50, rWord: "cincizeci" },
    ],
    recapIntro: "Numărăm din cinci în cinci:",
    recapWords: ["cinci", "zece", "cincisprezece", "douăzeci", "douăzeci și cinci", "treizeci", "treizeci și cinci", "patruzeci", "patruzeci și cinci", "cincizeci"],
    outro: ["Bravo! Ești harnică precum albinuțele!", "Urmează înmulțirea cu șase!"],
  },
  {
    n: 6,
    theme: { object: "ladybug", objectName: "buburuze", bg1: "#3f6212", bg2: "#65a30d", accent: "#f87171", card: "#fee2e2" },
    intro: [
      "Șase e dublul lui trei: dacă știi tabla cu trei, o dublezi și gata!",
      "Hai să cântăm!",
    ],
    trick: "× 6 = tabla cu 3, dublată!",
    verses: [
      { cue: "Buburuza pe terase:", a: 6, b: 1, r: 6, rWord: "șase" },
      { cue: "Peste frunze verzi ea trece:", a: 6, b: 2, r: 12, rWord: "doisprezece" },
      { cue: "Nicio gâză n-o întrece:", a: 6, b: 3, r: 18, rWord: "optsprezece" },
      { cue: "Aripioare de teatru:", a: 6, b: 4, r: 24, rWord: "douăzeci și patru" },
      { cue: "Vara zilele nu-s reci:", a: 6, b: 5, r: 30, rWord: "treizeci" },
      { cue: "Se ascund sub frunze-n case:", a: 6, b: 6, r: 36, rWord: "treizeci și șase" },
      { cue: "Numărăm punctele-apoi:", a: 6, b: 7, r: 42, rWord: "patruzeci și doi" },
      { cue: "Bobul de grâu e copt:", a: 6, b: 8, r: 48, rWord: "patruzeci și opt" },
      { cue: "Zboară-n cerul cel albastru:", a: 6, b: 9, r: 54, rWord: "cincizeci și patru" },
      { cue: "Prin grădină tu petreci:", a: 6, b: 10, r: 60, rWord: "șaizeci" },
    ],
    recapIntro: "Numărăm din șase în șase:",
    recapWords: ["șase", "doisprezece", "optsprezece", "douăzeci și patru", "treizeci", "treizeci și șase", "patruzeci și doi", "patruzeci și opt", "cincizeci și patru", "șaizeci"],
    outro: ["Bravo! Buburuzele îți poartă noroc la socotit!", "Urmează înmulțirea cu șapte!"],
  },
  {
    n: 7,
    theme: { object: "balloon", objectName: "baloane", bg1: "#581c87", bg2: "#9333ea", accent: "#fb923c", card: "#ffedd5" },
    intro: [
      "Șapte — ca zilele săptămânii! Tabla cu șapte cere puțin curaj, dar cu baloane zboară ușor!",
      "Hai să cântăm!",
    ],
    trick: "7 — ca zilele săptămânii!",
    verses: [
      { cue: "Un balon plutește-n noapte:", a: 7, b: 1, r: 7, rWord: "șapte" },
      { cue: "Vântul lin prin ele trece:", a: 7, b: 2, r: 14, rWord: "paisprezece" },
      { cue: "S-a prins unul de alunul:", a: 7, b: 3, r: 21, rWord: "douăzeci și unu" },
      { cue: "Grâul jos, pe câmp, e copt:", a: 7, b: 4, r: 28, rWord: "douăzeci și opt" },
      { cue: "Zboară peste cinci arici:", a: 7, b: 5, r: 35, rWord: "treizeci și cinci" },
      { cue: "Baloane pentru amândoi:", a: 7, b: 6, r: 42, rWord: "patruzeci și doi" },
      { cue: "Norii vin și-afară plouă:", a: 7, b: 7, r: 49, rWord: "patruzeci și nouă" },
      { cue: "Sfori subțiri ca de mătase:", a: 7, b: 8, r: 56, rWord: "cincizeci și șase" },
      { cue: "Zboară peste crâng și tei:", a: 7, b: 9, r: 63, rWord: "șaizeci și trei" },
      { cue: "Cu baloanele petreci:", a: 7, b: 10, r: 70, rWord: "șaptezeci" },
    ],
    recapIntro: "Numărăm din șapte în șapte:",
    recapWords: ["șapte", "paisprezece", "douăzeci și unu", "douăzeci și opt", "treizeci și cinci", "patruzeci și doi", "patruzeci și nouă", "cincizeci și șase", "șaizeci și trei", "șaptezeci"],
    outro: ["Bravo! Cea mai grea tablă zboară acum cu tine!", "Urmează înmulțirea cu opt!"],
  },
  {
    n: 8,
    theme: { object: "fish", objectName: "peștișori", bg1: "#164e63", bg2: "#0891b2", accent: "#fb923c", card: "#cffafe" },
    intro: [
      "Opt e dublul lui patru — iar caracatița are opt brațe, numai bune la socotit!",
      "Hai să cântăm!",
    ],
    trick: "× 8 = dublul lui × 4!",
    verses: [
      { cue: "Soarele pe lac e copt:", a: 8, b: 1, r: 8, rWord: "opt" },
      { cue: "Apa mării nu-i prea rece:", a: 8, b: 2, r: 16, rWord: "șaisprezece" },
      { cue: "Fac spectacol ca la teatru:", a: 8, b: 3, r: 24, rWord: "douăzeci și patru" },
      { cue: "Înoată-n cârd pe lângă noi:", a: 8, b: 4, r: 32, rWord: "treizeci și doi" },
      { cue: "Peste valuri mici și reci:", a: 8, b: 5, r: 40, rWord: "patruzeci" },
      { cue: "Coralul roșu pare copt:", a: 8, b: 6, r: 48, rWord: "patruzeci și opt" },
      { cue: "Alge fine ca mătase:", a: 8, b: 7, r: 56, rWord: "cincizeci și șase" },
      { cue: "Caracatița-i la teatru:", a: 8, b: 8, r: 64, rWord: "șaizeci și patru" },
      { cue: "Marea-i pentru amândoi:", a: 8, b: 9, r: 72, rWord: "șaptezeci și doi" },
      { cue: "Către mal acum te-ntreci:", a: 8, b: 10, r: 80, rWord: "optzeci" },
    ],
    recapIntro: "Numărăm din opt în opt:",
    recapWords: ["opt", "șaisprezece", "douăzeci și patru", "treizeci și doi", "patruzeci", "patruzeci și opt", "cincizeci și șase", "șaizeci și patru", "șaptezeci și doi", "optzeci"],
    outro: ["Bravo! Ai traversat oceanul numerelor!", "Urmează înmulțirea cu nouă!"],
  },
  {
    n: 9,
    theme: { object: "butterfly", objectName: "fluturași", bg1: "#4c1d95", bg2: "#7c3aed", accent: "#5eead4", card: "#ccfbf1" },
    intro: [
      "Truc magic la tabla cu nouă: adună cifrele rezultatului — fac mereu nouă!",
      "Optsprezece: unu plus opt — nouă!",
      "Hai să cântăm!",
    ],
    trick: "La × 9, cifrele rezultatului adunate dau 9!",
    verses: [
      { cue: "Fluturașul bea din rouă:", a: 9, b: 1, r: 9, rWord: "nouă" },
      { cue: "Peste pajiște el trece:", a: 9, b: 2, r: 18, rWord: "optsprezece" },
      { cue: "Zboară ziua, nu în noapte:", a: 9, b: 3, r: 27, rWord: "douăzeci și șapte" },
      { cue: "Se așază pe terase:", a: 9, b: 4, r: 36, rWord: "treizeci și șase" },
      { cue: "Aripi ca de licurici:", a: 9, b: 5, r: 45, rWord: "patruzeci și cinci" },
      { cue: "Cerul e senin, albastru:", a: 9, b: 6, r: 54, rWord: "cincizeci și patru" },
      { cue: "Se rotesc pe lângă tei:", a: 9, b: 7, r: 63, rWord: "șaizeci și trei" },
      { cue: "Vin în stol pe lângă noi:", a: 9, b: 8, r: 72, rWord: "șaptezeci și doi" },
      { cue: "Toamna scutură alunul:", a: 9, b: 9, r: 81, rWord: "optzeci și unu" },
      { cue: "Zboară peste mii de poteci:", a: 9, b: 10, r: 90, rWord: "nouăzeci" },
    ],
    recapIntro: "Numărăm din nouă în nouă:",
    recapWords: ["nouă", "optsprezece", "douăzeci și șapte", "treizeci și șase", "patruzeci și cinci", "cincizeci și patru", "șaizeci și trei", "șaptezeci și doi", "optzeci și unu", "nouăzeci"],
    outro: ["Bravo! Trucul lui nouă e magia ta!", "Urmează marele final: înmulțirea cu zece!"],
  },
  {
    n: 10,
    theme: { object: "candy", objectName: "bomboane", bg1: "#831843", bg2: "#db2777", accent: "#a5f3fc", card: "#fce7f3" },
    intro: [
      "Cea mai dulce tablă: la înmulțirea cu zece, pui un zero la coadă și gata!",
      "Hai să cântăm!",
    ],
    trick: "× 10 = pui un 0 la coadă!",
    verses: [
      { cue: "O bomboană dulce-rece:", a: 10, b: 1, r: 10, rWord: "zece" },
      { cue: "Cu prietenii petreci:", a: 10, b: 2, r: 20, rWord: "douăzeci" },
      { cue: "Jeleurile nu-s reci:", a: 10, b: 3, r: 30, rWord: "treizeci" },
      { cue: "Acadele dulci, întregi:", a: 10, b: 4, r: 40, rWord: "patruzeci" },
      { cue: "Jumătate-o dai, e simplu, deci:", a: 10, b: 5, r: 50, rWord: "cincizeci" },
      { cue: "Cu zerouri te întreci:", a: 10, b: 6, r: 60, rWord: "șaizeci" },
      { cue: "Borcanele nu-s goale, seci:", a: 10, b: 7, r: 70, rWord: "șaptezeci" },
      { cue: "Fugi la joacă pe poteci:", a: 10, b: 8, r: 80, rWord: "optzeci" },
      { cue: "Nouă pungi acum culegi:", a: 10, b: 9, r: 90, rWord: "nouăzeci" },
      { cue: "Tabla-ntreagă-i cunoscută:", a: 10, b: 10, r: 100, rWord: "o sută" },
    ],
    recapIntro: "Numărăm din zece în zece:",
    recapWords: ["zece", "douăzeci", "treizeci", "patruzeci", "cincizeci", "șaizeci", "șaptezeci", "optzeci", "nouăzeci", "o sută"],
    outro: ["Bravo! Ai ajuns la o sută!", "Toată tabla înmulțirii e acum a ta. Te felicit!"],
  },
];
